config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers
  end

  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout

  root 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, presence: true, length: { minimum: 50 }
  validates_uniqueness_of :best if :best == true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)

    if @answer.errors.any?
      flash[@answer.errors]
      redirect_to question_path(@question)
    else
      redirect_to question_path(@question)
    end
  end

  def edit
    @question = Question.find(params[:question_id])

    @best_answer = Answer.find_by(best: true)
    @best_answer.update_attribute(:best, false)

    @answer = Answer.find(params[:id])
    @answer.update_attribute(:best, true)

    redirect_to @question
  end

  private
    def answer_params
      params.require(:answer).permit(:description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  user = User.find_by(provider: auth["provider"], uid: auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to '/questions', notice: "Signed in!"
end

def destroy
  session[:user_id] = nil
  redirect_to '/', notice: "Signed out!"
end

protected

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = { hard_wrap:          true,
                escape_html:        true,
                prettify:           true,
                no_styles:          true }

    extensions = {
                autolink:           true,
                superscript:        true,
                no_intra_emphasis:  true,
                fenced_code_blocks: true }


    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= markdown(answer.description) %>
  <% if answer.best == true %>
    <div class = bestAnswer><strong>Best Answer</strong></div>
  <% else %>
    <%= link_to 'select as best answer', edit_question_answer_path(@question.id, answer.id) %>
  <% end %>
</li>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :description, 'Add an answer:' %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  Sign in with:
  <%= link_to "Github", "/auth/github"%>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:</h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, 'Question' %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description, 'Details' %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

<%= link_to 'Back to Question', question_path(@question) %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <ul>
    <li><%= markdown(question.title) %>
    | <%= link_to 'Link', question_path(question.id) %>
    | <%= link_to 'Edit', edit_question_path(question) %>
    | <%= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>
<% end %>

<%= link_to 'Ask New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back to Questions', questions_path %>

app/views/questions/show.html.erb
<h1><%= markdown(@question.title) %></h1>
    <%= link_to 'Edit', edit_question_path(@question) %>
  | <%= link_to 'Delete', question_path(@question), method: :delete,
                                                      data: { confirm: 'Are you sure?' } %>
<p>
  <%= markdown(@question.description) %>
</p>

<h2>Answers:</h2>
<ol>
  <% @question.answers.order(best: :desc, created_at: :desc).each do |answer| %>
    <%= render answer %>
  <% end %>
</ol>

<%= render "answers/form" %>

<%= link_to 'All Questions', questions_path %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>